services:
  app_vet:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://clinica_vet:5432/clinica_veterinaria
      DB_USER_NAME: postgres
      DB_PASSWORD: admin
    restart: always
    depends_on:
      clinica_vet:
        condition: service_healthy

  clinica_vet:
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clinica_veterinaria
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: